apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapi
  namespace: ec2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskapi
  template:
    metadata:
      labels:
        app: taskapi
    spec:
      containers:
        - name: taskapi
          image: 763383189399.dkr.ecr.ap-south-1.amazonaws.com/taskapi:amd64
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "sqlite:///./data.db"
          readinessProbe:
            httpGet: { path: /healthz, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet: { path: /healthz, port: 8000 }
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }